version: '3.3'

services:
  primary_mongo:
    build:
      context: .
      dockerfile: Dockerfile_mongo
    container_name: ${PRIMARY_CONTAINER_NAME}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${PRIMARY_IP}:${MONGO_PRIMARY_PORT}:27017"
    restart: always
    command: ["./initiate_replica_set.sh"]  # Запуск скрипта после запуска контейнера

  secondary_mongo:
    build:
      context: .
      dockerfile: Dockerfile_mongo
    container_name: ${SECONDARY_CONTAINER_NAME}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${SECONDARY_IP}:${MONGO_SECONDARY_PORT}:27017"
    restart: always
    depends_on:
      - primary_mongo
    command: ["./wait-for-it.sh", "${PRIMARY_CONTAINER_NAME}:${MONGO_PRIMARY_PORT}", "--", "docker-entrypoint.sh", "mongod", "--replSet", "rs0"]
